services:

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./shared/tempo:/etc
      - ./tempo-data:/var/tempo
    ports:
      - "4320:4317"  # otlp grpc
      - "4321:4318"  # otlp http
    entrypoint: sh -c "exec /tempo -config.file=/etc/tempo.yml"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./shared/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    entrypoint: sh -c "exec /bin/prometheus --config.file=/etc/prometheus/prometheus-local.yml --web.enable-remote-write-receiver"

  loki:
    image: grafana/loki:latest
    command:
      - "-config.file=/etc/loki/local-config.yaml"  
    volumes:
      - ./shared/loki/chunks:/loki/chunks/
      - ./shared/loki/rules:/loki/rules/
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    command:
      - "-config.file=/etc/promtail/config.yml"   
      - ./shared/logs:/var/log   
    depends_on:
      - loki   

  alloy:
    image: grafana/alloy:latest  
    command:
      - "-config.file=/etc/alloy/config.alloy"  
    volumes:
      - ./shared/alloy:/etc/alloy
    ports:
      - "4317:4317"  
      - "4318:4318"  
    entrypoint: sh -c "exec /bin/alloy run /etc/alloy/config.alloy"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./shared/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources
      - ./shared/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    ports:
      - "3000:3000"
    entrypoint: sh -c "exec grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana"

  shoehub:
    image: aussiearef/shoehub
    ports:
      - "8001:8080"

  orderservice:
    image: aussiearef/orderservice
  
  paymentservice:
    image: aussiearef/paymentservice
  
  stimulator:
    image: aussiearef/stimulator
    depends_on:
      - orderservice
      - paymentservice 
  
  influxdb:
    image: influxdb:latest
    volumes:
      - ./shared/influxdb:/var/lib/influxdb2
      - ./shared/influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  telegraf:
    image: telegraf:latest
    volumes:
      - ./shared/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket


volumes:
  prometheus-data:
  tempo-data:
  influxdb-data:
